# Site
name: "TimeNationPro.com"
title: "Home | TimeNationPro.com "
description: "Love watches? Look for the perfect watches to add to your watch collection with our buying guides, expert tips and reviews from TimeNationPro.com"
meta_description: "Love watches? Look for the perfect watches to add to your watch collection with our buying guides, expert tips and reviews from TimeNationPro.com"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
paginate: 12
baseurl: '/'
email: 'jumpingjoytechsolutions@gmail.com'
google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
sharethis: '<script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5a6b2fe4fb197a0011c589f6&product=sticky-share-buttons"></script>'

# Authors
authors:
  sal:
    name: jumpingjoytechsolutions
    display_name: JJTech
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: jumpingjoytechsolutions@gmail.com
    web:
    twitter: https://twitter.com/wowthemesnet
    description: "JJTech is the Administrator of all the content writers working at TimeNationPro.com."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Other
markdown: kramdown
highlighter: rouge
